apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-secrets
  namespace: karakeep
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: karakeep-secret
    creationPolicy: Owner
  data:
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        # CHANGE: Your 1Password item name for Karakeep secrets
        key: karakeep
        property: nextauth-secret
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        # CHANGE: same item as above
        key: karakeep
        property: meili-master-key
