apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:background-controller:volsync
  labels:
    app.kubernetes.io/component: background-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno
rules:
# Required for context apiCall to read the source Kopia credentials Secret
- apiGroups: [ "" ]
  resources: [ "secrets" ]
  verbs: [ "get", "list", "watch", "create", "update", "delete" ]
# Required to generate VolSync ReplicationSource and ReplicationDestination
- apiGroups: [ "volsync.backube" ]
  resources: [ "replicationsources", "replicationdestinations" ]
  verbs: [ "get", "list", "watch", "create", "update", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno:background-controller:volsync
  labels:
    app.kubernetes.io/component: background-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:background-controller:volsync
subjects:
- kind: ServiceAccount
  name: kyverno-background-controller
  namespace: kyverno
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:admission-controller:volsync
  labels:
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno
rules:
# Required for admission webhook to read Secrets via context apiCall
- apiGroups: [ "" ]
  resources: [ "secrets" ]
  verbs: [ "get", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno:admission-controller:volsync
  labels:
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:admission-controller:volsync
subjects:
- kind: ServiceAccount
  name: kyverno-admission-controller
  namespace: kyverno
