apiVersion: v1
kind: Service
metadata:
  name: karakeep-chrome
spec:
  selector:
    app: karakeep-chrome
  ports:
    - name: chrome
      protocol: TCP
      port: 9222
      targetPort: 9222
  type: ClusterIP
