apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: cloudnative-pg
  labels:
    app: immich
spec:
  instances: 1
  # VectorChord image for Immich vector search support
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.5-0.4.3
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    parameters:
      shared_buffers: "256MB"
      max_wal_size: "1GB"
      max_connections: "500"
      wal_compression: "on"
    pg_hba:
      - host all all 0.0.0.0/0 md5
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        # CHANGE: Create this secret before deploying (see secrets/immich-db-init-secret.yaml)
        name: immich-app-secret
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        - CREATE EXTENSION IF NOT EXISTS vector;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "immich";
        - GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "immich";
        - ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "immich";
        - ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "immich";
  storage:
    size: 20Gi
    storageClass: longhorn
  walStorage:
    size: 2Gi
    storageClass: longhorn
  enableSuperuserAccess: true
  monitoring:
    enablePodMonitor: false
