# This is a demo Secret class for SMB credentials
apiVersion: v1
kind: Secret
metadata:
  name: smbcreds
  namespace: csi-driver-smb
type: Opaque
data:
  username: <base64-encoded-username>
  password: <base64-encoded-password>
