apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: longhorn
  annotations:
    snapshot.storage.k8s.io/is-default-class: "true"
driver: driver.longhorn.io
deletionPolicy: Delete
