apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db-credentials
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: immich-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        # CHANGE: Your 1Password item name for Immich database credentials (same item as CNPG)
        key: immich-database
        property: username
    - secretKey: password
      remoteRef:
        # CHANGE: same item as above
        key: immich-database
        property: password
