apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: library
    # Enable automatic backup via Kyverno + VolSync
    backup: "hourly"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
  # dataSourceRef is added dynamically by Kyverno if a backup exists
