apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: machine-learning
    # No backup label - ML models are re-downloadable
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
