apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  blocks:
  - cidr: "192.168.1.240/28" # CHANGE: Your LB IP range. Usable IPs: .241-.254
  allowFirstLastIPs: false
