apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: infrastructure
spec:
  project: infrastructure
  source:
    # CHANGE: Your Git repo URL
    repoURL: https://github.com/mitchross/talos-argocd-proxmox-starter.git
    targetRevision: main
    path: infrastructure/networking/cilium
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
  - group: ""
    kind: ConfigMap
    name: hubble-ca-cert
    jsonPointers:
    - /data
  - kind: Secret
    name: cilium-ca
    namespace: kube-system
    jsonPointers:
      - /data/ca.crt
      - /data/ca.key
  - kind: Secret
    name: hubble-server-certs
    namespace: kube-system
    jsonPointers:
      - /data/ca.crt
      - /data/tls.crt
      - /data/tls.key
  - kind: Secret
    name: hubble-relay-client-certs
    namespace: kube-system
    jsonPointers:
      - /data/ca.crt
      - /data/tls.crt
      - /data/tls.key
