---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pvc-plumber
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    # CHANGE: Your Git repo URL
    repoURL: https://github.com/mitchross/talos-argocd-proxmox-starter.git
    targetRevision: main
    path: infrastructure/controllers/pvc-plumber
  destination:
    server: https://kubernetes.default.svc
    namespace: volsync-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
