apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-pvc
  namespace: karakeep
  labels:
    app: karakeep
    type: meilisearch-storage
    # Enable automatic backup via Kyverno + VolSync
    backup: "hourly"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
  # dataSourceRef is added dynamically by Kyverno if a backup exists
