apiVersion: v1
kind: Service
metadata:
  name: karakeep-meilisearch
spec:
  selector:
    app: karakeep-meilisearch
  ports:
    - name: http
      protocol: TCP
      port: 7700
      targetPort: 7700
  type: ClusterIP
