apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopia-credentials
  namespace: volsync-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: kopia-credentials
    creationPolicy: Owner
  data:
    - secretKey: KOPIA_PASSWORD
      remoteRef:
        # CHANGE: Your 1Password item name for Kopia backup password
        key: kopia
        property: password
