apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudnative-pg-operator-full-rbac
  labels:
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - events
  - serviceaccounts
  verbs:
  - "*"
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - "*"
