apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        # CHANGE: Your 1Password item name for the ESO connect token
        key: external-secrets
        property: token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
