apiVersion: v1
kind: Secret
metadata:
  name: immich-db-credentials
  # This goes in the Immich app namespace
  namespace: immich
type: Opaque
stringData:
  # CHANGE: Must match the values in immich-db-init-secret.yaml
  username: "immich"
  password: "CHANGE-ME-immich-db-password"
