apiVersion: v1
kind: Secret
metadata:
  name: karakeep-secret
  namespace: karakeep
type: Opaque
stringData:
  # CHANGE: Generate with: openssl rand -base64 32
  NEXTAUTH_SECRET: "CHANGE-ME-nextauth-secret"
  # CHANGE: Generate with: openssl rand -base64 32
  MEILI_MASTER_KEY: "CHANGE-ME-meili-master-key"
